linters:
  enable: # keep in ascending order
    - asasalint
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - gci
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gofumpt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - iface
    - inamedparam
    - ineffassign
    - intrange
    - lll
    - mirror
    - misspell
    - musttag
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - sloglint
    - staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  misspell:
    locale: US
  govet:
    enable-all: true
    disable:
      - shadow
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/sv-tools/mock-http-server)
  gofumpt:
    extra-rules: true
  lll:
    line-length: 120
    tab-width: 4
  goconst:
    min-len: 3
    min-occurrences: 3
  prealloc:
    for-loops: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint

issues:
  exclude-use-default: false
  exclude:
    - should have a package comment
