request_id_header: "X-Request-ID" # to be logged if present in the request headers
routes:
  - pattern: GET /users # see https://go.dev/blog/routing-enhancements for more information about patterns
    responses:
      - code: 200 # first 3 responses: 200 OK
        body: |
          [
            {
              "id": 1,
              "name": "John"
            },
            {
              "id": 2,
              "name": "Jane"
            }
          ]
        is_json: true
        repeat: 3
      - code: 500 # 4th response: 500 Internal Server Error
        repeat: 1
        body: "something is broken"
      - code: 200 # all other responses: 200 OK
        body: |
          [
            {
              "id": 1,
              "name": "John"
            },
            {
              "id": 2,
              "name": "Jane"
            }
          ]
        is_json: true
  - pattern: GET /users/{id}
    responses:
      - code: 200
        body: | # supports Go templates: https://pkg.go.dev/text/template
          {
            "id": "{{.PathValue "id"}}",
            "name": "John"
          }
        is_json: true
        repeat: 1
      - code: 404
        body: user "{{.PathValue "id"}}" not found
