name: "New Release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  GO: "1.24"

jobs:
  release-cli:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2 # immutable action, safe to use a version instead of hashtag

      - name: Install Go
        uses: actions/setup-go@v5.5.0 # immutable action, safe to use a version instead of hashtag
        with:
          go-version: ${{ env.GO }}

      - name: Allow arm Docker builds # https://github.com/linuxkit/linuxkit/tree/master/pkg/binfmt
        run: sudo docker run --privileged linuxkit/binfmt:v0.8

      - name: Docker Login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: sv-tools-bot
          password: ${{ secrets.BOT_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: svtools
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
        with:
          version: latest
          args: release --config .github/goreleaser-cli.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clear
        if: always()
        run: rm -f ${HOME}/.docker/config.json
